In [1]:
import torch

In [2]:
a = torch.randn(1, 2, 3, 4)
a.size()

torch.Size([1, 2, 3, 4])

# Transpose vs view

In [10]:
b = a.transpose(1, 2)  # Swaps 2nd and 3rd dimension
b.size()


torch.Size([1, 3, 2, 4])

In [11]:
print(a)
print(b)

tensor([[[[ 1.6395,  1.5620, -0.1664, -0.6549],
          [-0.0124, -0.5689,  0.4032, -0.3532],
          [ 0.2920,  0.7610, -1.4492, -1.3785]],

         [[ 0.4671,  0.3856,  2.4157, -0.9427],
          [ 1.6166, -0.0037,  0.0669, -1.5434],
          [-2.0009,  0.0901, -0.9708, -1.0613]]]])
tensor([[[[ 1.6395,  1.5620, -0.1664, -0.6549],
          [ 0.4671,  0.3856,  2.4157, -0.9427]],

         [[-0.0124, -0.5689,  0.4032, -0.3532],
          [ 1.6166, -0.0037,  0.0669, -1.5434]],

         [[ 0.2920,  0.7610, -1.4492, -1.3785],
          [-2.0009,  0.0901, -0.9708, -1.0613]]]])


In [12]:
c = a.view(1, 3, 2, 4)  # Does not change tensor layout in memory
c.size()

torch.Size([1, 3, 2, 4])

In [13]:
print(c)

tensor([[[[ 1.6395,  1.5620, -0.1664, -0.6549],
          [-0.0124, -0.5689,  0.4032, -0.3532]],

         [[ 0.2920,  0.7610, -1.4492, -1.3785],
          [ 0.4671,  0.3856,  2.4157, -0.9427]],

         [[ 1.6166, -0.0037,  0.0669, -1.5434],
          [-2.0009,  0.0901, -0.9708, -1.0613]]]])


In [14]:
a.size()

torch.Size([1, 2, 3, 4])

In [15]:
print(a.transpose(-1,-2).size())
print(a.transpose(-1,-2))

torch.Size([1, 2, 4, 3])
tensor([[[[ 1.6395, -0.0124,  0.2920],
          [ 1.5620, -0.5689,  0.7610],
          [-0.1664,  0.4032, -1.4492],
          [-0.6549, -0.3532, -1.3785]],

         [[ 0.4671,  1.6166, -2.0009],
          [ 0.3856, -0.0037,  0.0901],
          [ 2.4157,  0.0669, -0.9708],
          [-0.9427, -1.5434, -1.0613]]]])


In [17]:
print(a.transpose(-1,-3).size())
print(a.transpose(-1,-3))

torch.Size([1, 4, 3, 2])
tensor([[[[ 1.6395,  0.4671],
          [-0.0124,  1.6166],
          [ 0.2920, -2.0009]],

         [[ 1.5620,  0.3856],
          [-0.5689, -0.0037],
          [ 0.7610,  0.0901]],

         [[-0.1664,  2.4157],
          [ 0.4032,  0.0669],
          [-1.4492, -0.9708]],

         [[-0.6549, -0.9427],
          [-0.3532, -1.5434],
          [-1.3785, -1.0613]]]])


In [18]:
a.size()

torch.Size([1, 2, 3, 4])

In [24]:
(a @ a.transpose(-1,-2)).size()

torch.Size([1, 2, 3, 3])