In [1]:
import numpy as np

In [85]:
def pagerank(T, epsilon= 1e-20):
    n = len(T)
    v = np.array([1.0/n for _ in range(n)])
    while True:
        v_next = np.dot(v, T.transpose())
        if np.linalg.norm(v_next-v, 2) < epsilon:
            break
        v = v_next
    return v_next

In [86]:
T1 = np.random.random((10,10))
T2 = np.random.random((10,10))
T1 = T1/T1.sum(axis=0)
T2 = T2/T2.sum(axis=0)

In [87]:
v1 = pagerank(T1)
v2 = pagerank(T2)

In [88]:
print(v1, v2)

[0.1043339  0.08332381 0.09027928 0.09011463 0.08926088 0.08687108
 0.0819603  0.13572007 0.11038573 0.12775033] [0.09661106 0.0880347  0.08077362 0.11672595 0.0952488  0.11513279
 0.1365101  0.0593386  0.10920386 0.10242053]


In [89]:
T = (T1 + 2*T2)/3

In [90]:
T

array([[0.14175453, 0.03899807, 0.10863467, 0.1176916 , 0.06970691,
        0.10916465, 0.14147737, 0.05642156, 0.07332262, 0.0933083 ],
       [0.03704695, 0.12075778, 0.16910632, 0.0719973 , 0.0842626 ,
        0.05264206, 0.03694371, 0.15172985, 0.08492765, 0.11441113],
       [0.11811124, 0.14000536, 0.02333961, 0.16083611, 0.07894549,
        0.05607732, 0.09421231, 0.0127928 , 0.06188451, 0.08290415],
       [0.02691141, 0.10047432, 0.11372864, 0.0979078 , 0.05811528,
        0.12318437, 0.09535671, 0.20814456, 0.23918538, 0.05840103],
       [0.01245361, 0.07521059, 0.13394393, 0.03527564, 0.07894819,
        0.13174363, 0.17437698, 0.1259307 , 0.04649109, 0.10664751],
       [0.18658305, 0.09729163, 0.09892074, 0.08860475, 0.15051768,
        0.10596484, 0.01906185, 0.08867812, 0.05635364, 0.17083856],
       [0.11747282, 0.1283377 , 0.10217007, 0.09539394, 0.16332765,
        0.15018472, 0.12885553, 0.15969095, 0.14190023, 0.01698873],
       [0.09301853, 0.12937921, 0.0508166

In [95]:
v = pagerank(T, 1e-15)

In [96]:
v

array([0.09713754, 0.08887923, 0.08500891, 0.11158182, 0.0922874 ,
       0.10447942, 0.11896132, 0.08443708, 0.10845095, 0.10877631])

In [97]:
(v1 + 2*v2)/3

array([0.09918534, 0.0864644 , 0.08394217, 0.10785551, 0.09325283,
       0.10571222, 0.11832683, 0.08479909, 0.10959782, 0.11086379])